FROM resin/%%RESIN_MACHINE_NAME%%-python

RUN apt-get update \
	&& apt-get install -y \
		python-pygame \
	&& rm -rf /var/lib/apt/lists/*

ENV INITSYSTEM on

ENV DEVICE %%RESIN_MACHINE_NAME%% 

COPY . /usr/src/app

WORKDIR /usr/src/app

CMD /usr/src/app/start.sh
